AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*'

Style/Documentation:
  Enabled: false